import { Poppins, Petrona } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/landing/Navbar";
import NavbarSmall from "./ui/landing/NavbarSmall";
import Head from "next/head";

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const petrona = Petrona({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>My Next.js App</title>
        <link rel="icon" href="/favicon.png" />
      </Head>
      <body className={poppins.className}>
        <div>
          <div className="lg:block hidden">
            <Navbar />
          </div>
          <div className="lg:hidden block">
            <NavbarSmall />
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
